// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaGz8WlWKkIl9JTSS2gVQhS_wg03N6G7E',
    appId: '1:651564935590:web:0b3b426153f872fbb84767',
    messagingSenderId: '651564935590',
    projectId: 'connect-hub-9243c',
    authDomain: 'connect-hub-9243c.firebaseapp.com',
    storageBucket: 'connect-hub-9243c.firebasestorage.app',
    measurementId: 'G-T3WQ31ZKZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAaQBc2MWjSW47N26Hle2hFB4SGgWH2f4',
    appId: '1:651564935590:android:fddfdaff37426f65b84767',
    messagingSenderId: '651564935590',
    projectId: 'connect-hub-9243c',
    storageBucket: 'connect-hub-9243c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkm1uP9AjuPD_I56LoJ8baenphKB41khM',
    appId: '1:651564935590:ios:4cae54f725e48282b84767',
    messagingSenderId: '651564935590',
    projectId: 'connect-hub-9243c',
    storageBucket: 'connect-hub-9243c.firebasestorage.app',
    iosBundleId: 'com.example.connectHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkm1uP9AjuPD_I56LoJ8baenphKB41khM',
    appId: '1:651564935590:ios:4cae54f725e48282b84767',
    messagingSenderId: '651564935590',
    projectId: 'connect-hub-9243c',
    storageBucket: 'connect-hub-9243c.firebasestorage.app',
    iosBundleId: 'com.example.connectHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaGz8WlWKkIl9JTSS2gVQhS_wg03N6G7E',
    appId: '1:651564935590:web:a984502b7d412b6cb84767',
    messagingSenderId: '651564935590',
    projectId: 'connect-hub-9243c',
    authDomain: 'connect-hub-9243c.firebaseapp.com',
    storageBucket: 'connect-hub-9243c.firebasestorage.app',
    measurementId: 'G-74E6XSYD5C',
  );
}
